lib/loader/index.js, test/unit/loader/index.spec.js
We were unsafely calling `callback` on any subsequent loads after the first of a url.
ezpz check that we just missed.
Also added unit tests that fail in phantom but pass in chrome for some reason. *shrug*
=> JST-79: check for callback existence before invoking

.travis.yml, package.json
[Tests are breaking](https://travis-ci.org/bazaarvoice/bv-ui-core/builds/209881734) with 0.12.18. This is reproducible on master.
This tells Travis to use latest, and documents it in package.json for users.
=> Use latest Node

lib/staticAssetLoader/index.js
lol at throwing an error when trying to throw an error because we used the wrong name.
=> UIA-8376: Fix reference error when reporting failed static assets

lib/namespacer/index.js
Currently, namespaces [cannot replace existing namespaces](https://github.com/bazaarvoice/bv-ui-core/blob/master/lib/namespacer/index.js#L88). I'd like to propose that we disallow namespaces being replaced by different values in general.
```javascript
> window.BV
{ a: 1 }
> window.BV.b = 2  // the namespace is extensible
{ a: 1, b: 2 }
> window.BV = { c: 3 }
> window.BV        // but not writable
{ a: 1, b: 2 }     
```
The motivation for this is that my namespace is shared by different runtime consumers, and certain properties on the namespace are guaranteed to be read-only. A consumer could work around this by replacing the entire namespace with writeable properties, which I want to disallow.
P.S. This seems to be a tricky unit test to write. Something in the test runner doesn't seem to …
=> Prevent namespaces from being replaced or removed

.gitignore, lib/application/README.md, lib/application/index.js, test/unit/application/index.spec.js
[SWAT-1020](https://bits.bazaarvoice.com/jira/browse/SWAT-1020)
Per a discussion yesterday, it would be nice to be able to queue up callbacks for application classes, which wouldn't fire until the application was deemed 'loaded' and available for interacting with. The intent is that applications loaded via BV Loader should automatically kick off the callback queue once they're finished being loaded.
After some discussing about the interface, we came to an agreement that in environments where ES6 Promises were not available, `ready` will behave as a simple callback aggregator, and return undefined: e.g. `app.ready(callback1); app.ready(callbackN);`. In environments where Promises *are* available, either due to native support, or polyfilled support, it will provide the same callback …
=> SWAT-1020 -- Adding new 'ready' function/Promise interface

lib/getOriginalConstructor/README.md, lib/getOriginalConstructor/index.js, test/unit/getOriginalConstructor/index.spec.js
[SWAT-1609](https://bits.bazaarvoice.com/jira/browse/SWAT-1609)
In some situations, clients are overriding prototype functions of primitives (or using Prototype.js, which does that), and some prototype functions we're relying on can throw unexpected errors.
Added a method to fetch an original version of the constructor from a throwaway iframe.
1. Check out this PR and run the tests.
=> SWAT-1609 -- Adding getOriginalConstructor function

lib/getOriginalConstructor/index.js, test/unit/getOriginalConstructor/index.spec.js
IE11 was throwing an error because the constructors hash was being keyed by constructor.name, which doesn't exist in IE11. I added a regex so that we could prefer constructor.name where it was supported, and fallback to regex'ing a name out of the function declaration as a backup for browsers where that wasn't supported. That fixes that issue.
Secondly, there was an issue with returning cached versions of these lookups. The original implementation would create an iframe, stick it in the head, return the constructor from it, and then remove it from the head. In future calls, the cached function would be returned, which would cause IE11 to throw an error about trying to execute code from freed scripts. The options to fix this were to create/attach/detach the iframe on every request to this …
=> SWAT-1609 -- Bug fixes for IE11

lib/polyfills/README.md, lib/polyfills/fetch.js, package.json, test/unit/polyfills/fetch.spec.js, test/unit/polyfills/promise.spec.js
[SWAT-1242](https://bits.bazaarvoice.com/jira/browse/SWAT-1242)
We want to be able to use the `fetch` API in our products, but IE11 doesn't support it, and we don't want to unnecessarily polyfill if we natively support it. We also want to make sure that if an existing polyfill is in place, that we use our own official polyfill (in case the existing polyfill doesn't do it to spec). All of this should be done without interfering with the global namespace, so as not to disrupt any client code that may be dependent on their own fetch polyfill.
Wrap whatwg-fetch in a module that exposes either the native fetch function (and supporting constructor classes for Headers/Request/Response), or the whatwg-fetch versions of fetch and its supporting constructors.
1. Check out this PR.
2. Run the tests, …
=> SWAT-1242 -- Adding fetch polyfill module

lib/polyfills/fetch.js
When certain properties were undefined we were still creating a property, which passes the `in` check that whatwg-fetch does.
We actually only need to add to the self object the global properties that exist.
I'm unsure how to write unit tests for this, but in practice it worked on IE11.
=> SWAT-DEV: Fix for whatwg-fetch property existence.

README.md, karma.conf.js, lib/getOriginalConstructor/README.md, lib/getOriginalConstructor/index.js, lib/waitForBody/README.md, lib/waitForBody/index.js, test/unit/getOriginalConstructor/index.spec.js
We were previously appending the iframe to document.head, but it seems that in some environments, that causes the iframe's `contentWindow` property to be null, and errors when trying to pull the primitive reference from it. We're now appending it to document.body instead, since it's an empty iframe anyway, with `src="about:blank"`, which appears to clear up that issue.
=> SWAT-2071 -- Fixing a bug in getOriginalConstructor

lib/domainPolice/index.js
As you can see from [this diff](https://github.com/bazaarvoice/bv-ui-core/compare/v1.2.1...tnunamak:fix-ie#diff-2018b927d3eb400bb9d2df501087c0d3L76), the only thing I have changed here relative to v1.2.1 is a comment.
=> SWAT-4956: Revert Object.assign usage for IE11 compatibility

lib/getOriginalConstructor/index.js
The iframe being injected onto the DOM is not ADA compliant. 
Since the iframe contains content that is hidden to users, we can hide the iframe to make it ADA compliant. I used these two articles as references:
https://developer.paciellogroup.com/blog/2010/04/making-sure-hidden-frames-are-hidden/
http://davidmacd.com/blog/is-title-attribute-on-iframe-required-by-wcag.html
@tnunamak I'm not sure how to verify that the iframe now contains the content that I've added. I believe I need to run this in bv-loader since bv-ui-core is imported there, but I don't know how to run bv-loader and how to import the local version of bv-ui-core on my computer.
=> Make iframe ADA compliant by hiding iframe and adding title

lib/global/index.js
Problem
The Global object is being exposed with CSP violations. 
Without `unsafe-eval` directive value of CSP the code can't be executed and thus Firebird app fails to run on the client end.
This is a part of changes for basic support of CSP scoped in CCS-34125.
Solution
We can provide a reference to the global object by using es6-shim alternative to globalThis global object:
*  the below solution works in ES3+ environment and doesn't violates CSP in Chrome apps 
*  see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis
We expect this module to be published with new release version which we can update on Firebird project and deploy. Local testing was performed with the package reference like this  "bv-ui-core": …
=> CCS-34126: apply CSP-compatible fix

lib/global/index.js
**Problem**
We migrated scoutfile dependency 2.0.0 -> 4.0.1  on Firebird repo to apply CSP-compatible fix.
old scoutfile(v2.0.0) has bv-ui-core v0.5.0 as its dependency
new  scoutfile(v4.0.1) includes bv-ui-core v2.1.1
The problem here with [this changes](https://github.com/bazaarvoice/bv-ui-core/commit/8ac7f0a0a470276cdc3800a80553cf7a1a971ca4) on bv-ui-core 0.11.1 which breaks Site Preview and mixed integration (Firebird + SWAT).
**Solution**
A solution would be to apply this changes on bv-ui-core v0.5.0 and release bv-ui-core v0.5.1 containing these changes.
Based on this new package we can update scoutfile and that should be enough :)
=> apply CSP fix to v0.5.0 version

lib/global/index.js
Safari 12.0 does not support `globalThis`, so before this change, `self` was selected as the global in that environment. I observed a case where the global context was then defined to be a `<script>` object but where the window would be preferable.
Any objections?
Btw, [this article](https://mathiasbynens.be/notes/globalthis) describes some of the differences of the different values used here.
=> Prefer window over self as the global object

lib/evented/index.js, test/unit/evented/index.spec.js
[SWAT-5709](https://bits.bazaarvoice.com/jira/browse/SWAT-5709]
As Robby has documented in the above Jira ticket and also [this Github issue](https://github.com/bazaarvoice/bv-ui-core/issues/96), the `evented` wrapper is currently swallowing errors whenever a `.trigger` event fails. This obviously makes debugging a lot harder, and could potentially also be swallowing significant bugs that we just don't know about.
I've added a `.setErrorHandler` method to the `evented` constructor. This method takes a callback to be executed whenever a `.trigger` method ends up throwing an error.
`.setErrorHandler` is called the very first time a call to `.on` is made, no matter what, and can also be called at any time to change the behavior of the handler. No matter happens, the error is logged to the …
=> SWAT-5709: Add error handling to evented.trigger

lib/api/statistics.js
[SWAT-5931](https://bits.bazaarvoice.com/jira/browse/SWAT-5931)
The ticket [SWAT-5904](https://bits.bazaarvoice.com/jira/browse/SWAT-5904) requires changes in statistics request url to get incentivized content.
Updated  **lib/statistics.js** by adding additional query param in request url - **incentivizedStats**
1. Open locally  [Inline Ratings](https://github.com/bazaarvoice/inline-ratings) repo or install it you do not have it yet.
2. Go to **node_modules/bv-ui-core/lib/api/statistics.js** and update this file according to current changes.
3. Go to **src/util/api.js** on line `46` update results variable declaration by adding new key - **showIncentivizedReviews**.  The whole declaration should look like this:
```
const results = await getStatistics({
productIds: filteredProductIds, …
```
=> SWAT-5931:added incentivizedStats query param to statistics request url

lib/cookie/README.md, lib/cookie/index.js, lib/cookieConsent/README.md, lib/cookieConsent/index.js, package-lock.json, package.json, test/unit/cookieConsent/index.spec.js
[PD-177966](https://bazaarvoice.atlassian.net/browse/PD-177966)
[PD-177967](https://bazaarvoice.atlassian.net/browse/PD-177967)
- Feature
-  Cookie module should listen to the add consent event when it creates a cookie
- Cookie consent module should have a function which passes the entire consent object to a callback whenever there is any change in the consent 
- subscribed to the add event in the cookie module when creating a cookie 
- Exposed a new method called subscribeStore. Which accepts a callback function and passes the store object as the param ameter
- Existing test cases work 
- Use the new module and run the subscribeStore command to test it out
=> Adding a new listener to cookieConsent

catalog-info.yaml, lib/README.md, mkdocs.yaml
Backstage is a centralized platform which supports the cataloguing and documentation of all the repositories of an organisation.
Adding the necessary files to do the same.
The end result can be checked in 
https://backstage.qa.bazaarvoice.com/catalog/default/component/bv-ui-core/
=> Integration of Backstage 

.eslintrc, README.md, lib/queryShadowDom/README.md, lib/queryShadowDom/index.js, package-lock.json, package.json
[PD-205376](https://bazaarvoice.atlassian.net/browse/PD-205376)
- Feature 
Added utility method to get bv container elements from open shadow dom.
- Added utility method to get bv container elements from open shadow dom.
1. `shadowQuerySelectorAll` - `(node, matchSelector)` - Returns Nodes matching with match selector.
2. `findShadowRoots` - `(node)` - Returns a list of all the shadow roots found in the given root element and its descendants.
3. `filterShadowHosts` - `(node)` - Returns NodeFilter.
4. `findElementsInShadowDomByMatchSector` - `(node, matchSelector)` - Returns a NodeList of all elements within the shadow DOM of the shadowElement parameter that match the matchSelector parameter.
- using npm link to test the changes in local in bv-loader
This will be released as a new minor …
=> PD-205376 - Added utility method to get bv container elements from open shadow dom.

lib/global/index.js, package-lock.json, package.json, test/unit/global/index.spec.js
[PD-215136](https://bazaarvoice.atlassian.net/browse/PD-215136)
[Approach document](https://bazaarvoice.atlassian.net/wiki/spaces/DEV/pages/edit-v2/78462714460)
- Bug
- When a client uses transpilations for its esModule files with default exports, these transpilations sets __esModule to true to each of such module. For Example: If the client has a esModule which exports globalThis/global/window object by default. It sets __esModule to true, to value after resolution of the modulie, in this case, window.__esModule is set
- SWAT apps uses webpack as bundler, webpack adds logic to import such default export esModule's by a condition, if esModule is set, then return module's default.
- This causes issue as this tries to return windows.default , which do not exist, when importing global.js 
- …
=> [utility fix] fix issue when global is polluted

lib/global/index.js, package-lock.json, package.json
[PD-215136](https://bazaarvoice.atlassian.net/browse/PD-215136)
- Bug
- BV loader throws ''set' on proxy: trap returned falsish for property javascript' error when latest global of bv-ui-core
- This is because, BV namespace has its own proxy and a setter which tries to set properties to window.BV
- global do not return any boolean in its setter method - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/set#return_value
- Add boolean return for global's return method
- N/A
- Patch - 2.8.2
[PD-215136]: https://bazaarvoice.atlassian.net/browse/PD-215136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: added boolean return for global set to fix Proxy set trapped error

lib/loader/index.js, package-lock.json, package.json
[PD-234259](https://bazaarvoice.atlassian.net/browse/PD-234259)
- Bug
The client is seeing an error in the console "Uncaught TypeError: Cannot read properties of null (reading 'removeChild')"
As a fix now we are adding a condition if script is having parent node then we are allowing to remove the child by doing so it will not throw any error in the console.
**Before fix**
**After fix:**
Note: console error which is observed because clients are on lower version and we used redirection for testing so.
[PD-234259]: https://bazaarvoice.atlassian.net/browse/PD-234259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PD-234259: TraegerService: Console error "Remove Child"

lib/bvFetch/index.js
[PD-230727](https://bazaarvoice.atlassian.net/browse/PD-230727)
Creating bvFetch module whose purpose is to cache duplicate api calls. Need to resolve error `Error: TypeError: Already read`
Created the module which caches the api responses based on the url. 
Made change to return cloned promise to fix the error.
[PD-230727]: https://bazaarvoice.atlassian.net/browse/PD-230727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> returning cloned promise for bvFetch module

lib/bvFetch/README.md, lib/bvFetch/index.js, package-lock.json, package.json, test/unit/bvFetch/index.spec.js
[PD-237465](https://bazaarvoice.atlassian.net/browse/PD-237465)
[PD-237445](https://bazaarvoice.atlassian.net/browse/PD-237445)
Fixing bugs in bvFetch module. in firefox when adBlocker extenstion is enabled the cached response is null.
Added a condition to get body from response.body when window fetch is used. Added cache expiry mechanism and added cache limit of 10 MB
[PD-237465]: https://bazaarvoice.atlassian.net/browse/PD-237465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PD-237445]: https://bazaarvoice.atlassian.net/browse/PD-237445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> adding cache expiry mechanisms and fixing PD-237465, PD-237445

lib/bvFetch/index.js, package-lock.json, package.json, test/unit/bvFetch/index.spec.js
An error is being thrown in performance test page.
[PD-238557](https://bazaarvoice.atlassian.net/browse/PD-238557)
- Bug
- Error is being thrown in performance test page. Because the response body is being used twice, once for checking size once for caching response body.
- Point 1
- Creating separate clone of the response to check for size and caching.
- As Part of the verification, deploy version with bvFetch and check that there are no console errors in the test page on pageLoad.
[PD-235835]: https://bazaarvoice.atlassian.net/browse/PD-235835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PD-238557]: https://bazaarvoice.atlassian.net/browse/PD-238557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
=> Bv fetch changes to fix, PD-238557

lib/bvFetch/index.js, package-lock.json, package.json
[PD-254370](https://bazaarvoice.atlassian.net/browse/PD-254370)
- Bug
- Some clients have a feature that clears the cache on every reload. This action removes the bvFetch cache, and on the next reload, when the webpage tries to access the cache, the reviews container fails due to the cache no longer being available.
- The solution is to ensure that when the page attempts to access the cache and finds it does not exist, it is recommended to trigger the fetch call again to the API.
[PD-254370]: https://bazaarvoice.atlassian.net/browse/PD-254370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PD-254370] : bv-fetch catch clear issue resolved

lib/bvFetch/index.js, package-lock.json, package.json
[PD-254370](https://bazaarvoice.atlassian.net/browse/PD-254370)
- Bug
- Some clients have a feature that clears the cache on every reload. This action removes the bvFetch cache, and on the next reload, when the webpage tries to access the cache, the reviews container fails due to the cache no longer being available.
- The solution is to ensure that when the page attempts to access the cache and finds it does not exist, it is recommended to trigger the fetch call again to the API.
[PD-254370]: https://bazaarvoice.atlassian.net/browse/PD-254370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Csat pd 254370 bv fetch issue

lib/bvFetch/index.js, package-lock.json, package.json
* [PD-254370]: Bv fetch issue resolved
* Release 2.9.5
* Release 2.9.6
Fixed BVFetch deleted cache key issue.
Manually removing the cache key if the cache for that key is not available.
[PD-254370]: https://bazaarvoice.atlassian.net/browse/PD-254370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Csat pd 254370 bv fetch issue (#144)

lib/bvFetch/README.md, lib/bvFetch/index.js, package-lock.json, package.json, test/unit/bvFetch/index.spec.js
[PD-260762](https://bazaarvoice.atlassian.net/browse/PD-260762)
- Bug
- The bvFetch module does not honor the change in headers while retrieving the cached response
- When storing the response in cache the request headers are not a part of the cache key. Making changes so that the cache key is a request so that when retrieving the cache from the cache storage the request headers are available.
- For BFD the response obj in the api response should be passed to the error handling function
[PD-260762]: https://bazaarvoice.atlassian.net/browse/PD-260762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> allowing bvFetch to honor change the request headers while caching

lib/bvFetch/README.md, lib/bvFetch/index.js, package-lock.json, package.json
[PD-286544](https://bazaarvoice.atlassian.net/browse/PD-286544)
- Bug
- When traceId is added to the BFD api calls the caching mechanism breaks
- When duplicate api calls happens on the PDP in one load the api calls are repeated.
- Adding functionality to exclude certain headers from the cacheKey
- The ongoing promise is not returned when the duplicate api call happens on the page. Since the cacheKey is a request the key check is failing. Fixed this issue by stringyfing the request content.
[PD-286544]: https://bazaarvoice.atlassian.net/browse/PD-286544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> adding the exclude Headers functionality to exclude certain headers from the cacheKey
